### ISSUE TITLE
no photos?

### ISSUE THREAD

**Issue by davidsean** [dfo-gulf-science/ANDES-description-report-2023#32]
no mention of photo capabilities, I feel it's a big enough deal to try to squeeze in the report.
Upvote and I'll take care to add it in the Results section.

**Comment by gddaiss-dmsaisb** [comment]
I agree

**Comment by ricardd** [comment]
good point, the draft report pre-dates the development of the photo capabilities, but sure let's add it, I will chat with @stoyelq about this

**Comment by davidsean** [comment]
Awesome, thanks Quentin!

I remember reading something along the lines of "imaging as part of a future addition to Andes". Now that the imaging part is included, we'd have to re-read those bits to see if they still make sense. I think it happened at a couple of places.

**Comment by ricardd** [comment]
I removed the last part of the sentence mentioning this in the discussion, see pull request #37 .
